version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mixsurveyrootpass
      MARIADB_DATABASE: mixsurvey
      MARIADB_USER: mixsurvey
      MARIADB_PASSWORD: mixsurveypass
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 13306:3306